<?xml version="1.0" encoding="utf-8"?>
<report
	progress="">
	<activity
		result="Success"
		duration="0ms"
		durationms="0"
		type="root"
		rid="15c9713605305ccc"
		totalerrorcount="2"
		totalwarningcount="0"
		totalsuccesstestcasecount="0"
		totalfailedtestcasecount="1"
		totalblockedtestcasecount="0"
		childsuccesscount="0"
		childfailedcount="1"
		childblockedcount="0"
		totalsuccesscount="0"
		totalfailedcount="2"
		totalblockedcount="0"
		totalmaintenancemodecount="0"
		user="administrator"
		rxversion="8.2.1.0"
		host="CIGNITI-W12R2-2"
		osversion="Windows Server 2012 R2 64bit"
		runtimeversion="4.0.30319.42000"
		procarch="32bit"
		oslanguage="en-US"
		dtnlanguage="en-US"
		screenresolution="1366x768"
		timestamp="4/8/2019 6:22:31 AM"
		timestampiso="2019-04-08T13:22:31"
		endtime="4/8/2019 6:22:32 AM"
		timeoutfactor="1">
		<detail>
			Ranorex Testscript
		</detail>
		<activity
			result="Failed"
			duration="347ms"
			durationms="347"
			type="test-suite"
			rid="bd1d1b779217b00"
			totalerrorcount="2"
			totalwarningcount="0"
			totalsuccesstestcasecount="0"
			totalfailedtestcasecount="1"
			totalblockedtestcasecount="0"
			childsuccesscount="0"
			childfailedcount="1"
			childblockedcount="0"
			totalsuccesscount="0"
			totalfailedcount="2"
			totalblockedcount="0"
			totalmaintenancemodecount="0"
			testsuitename="AutomationSQLdm"
			headertext="AutomationSQLdm"
			runconfigname="TestRun"
			runlabel="">
			<params>
			</params>
			<detail>
				False
			</detail>
			<activity
				result="Failed"
				duration="280ms"
				durationms="280"
				type="smart-folder"
				rid="b2773a6b9c1d771"
				totalerrorcount="2"
				totalwarningcount="0"
				totalsuccesstestcasecount="0"
				totalfailedtestcasecount="1"
				totalblockedtestcasecount="0"
				childsuccesscount="0"
				childfailedcount="2"
				childblockedcount="0"
				totalsuccesscount="0"
				totalfailedcount="2"
				totalblockedcount="0"
				totalmaintenancemodecount="0"
				testcontainername="T721944"
				testcontainerid="24e492a3-ae95-41c7-8888-8e97327b45b7"
				headertext="T721944"
				displayName="T721944"
				iteration="1"
				activity-exectype="execute"
				conditionstate="none">
				<activity
					result="Failed"
					duration="176ms"
					durationms="176"
					type="test-case"
					rid="2363ef29e82c5302"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="1"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="1"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="1"
					totalblockedcount="0"
					totalmaintenancemodecount="0"
					testcontainername="Groom_forecasting_data_older_than_XX_days_option_is_shown"
					testcontainerid="158b2417-a6c5-4f95-af24-460568a301c2"
					headertext="Groom_forecasting_data_older_than_XX_days_option_is_shown"
					displayName="Groom_forecasting_data_older_than_XX_days_option_is_shown"
					iteration="1"
					activity-exectype="execute"
					conditionstate="none">
					<activity
						result="Failed"
						duration="139ms"
						durationms="139"
						type="test-module"
						rid="19c0f796a07a89a7"
						totalerrorcount="1"
						totalwarningcount="0"
						totalsuccesstestcasecount="0"
						totalfailedtestcasecount="0"
						totalblockedtestcasecount="0"
						childsuccesscount="0"
						childfailedcount="0"
						childblockedcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						totalmaintenancemodecount="0"
						modulename="VerifyGroomForecastingData"
						displayName="VerifyGroomForecastingData"
						moduleid="07961294-8c4f-409c-baeb-06255200a69c"
						moduletype="UserCode"
						iteration="1"
						activity-exectype="runiteration"
						testentry-activity-type="testmodule">
						<errormessage>
							Exception has been thrown by the target of an invocation.
						</errormessage>
						<item
							timeRelativeToTestSuiteStartTime="00:00.370"
							timeRelativeToTestModuleStartTime="00:00.016"
							timeWallClock="06:22:31"
							time="00:00.370"
							level="Error"
							category="Module">
							<message>
								Exception has been thrown by the target of an invocation.<br/>The type initializer for 'AutomationSQLdm.Configuration.Config' threw an exception.<br/>Object reference not set to an instance of an object.
							</message>
							<metainfo
								stacktrace="   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#13;&#10;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#13;&#10;   at System.Activator.CreateInstance(Type type)&#13;&#10;   at Ranorex.Core.Testing.TestModuleActivator.DefaultFactoryMethod.CreateFactory()&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.InitializeTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.RunWithRepeats(DataContext parentDataContext, ErrorBehavior errorBehavior)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.Run(DataContext parentDataContext, Boolean childSkip)"
								loglvl="Error">
							</metainfo>
						</item>
					</activity>
				</activity>
				<activity
					result="Failed"
					duration="89ms"
					durationms="89"
					type="teardown-container"
					rid="c210d694ad9ad0c"
					totalerrorcount="1"
					totalwarningcount="0"
					totalsuccesstestcasecount="0"
					totalfailedtestcasecount="0"
					totalblockedtestcasecount="0"
					childsuccesscount="0"
					childfailedcount="1"
					childblockedcount="0"
					totalsuccesscount="0"
					totalfailedcount="0"
					totalblockedcount="0"
					totalmaintenancemodecount="0">
					<activity
						result="Failed"
						duration="71ms"
						durationms="71"
						type="test-module"
						rid="fc3b0d209e96240"
						totalerrorcount="1"
						totalwarningcount="0"
						totalsuccesstestcasecount="0"
						totalfailedtestcasecount="0"
						totalblockedtestcasecount="0"
						childsuccesscount="0"
						childfailedcount="0"
						childblockedcount="0"
						totalsuccesscount="0"
						totalfailedcount="0"
						totalblockedcount="0"
						totalmaintenancemodecount="0"
						modulename="CloseSQLdm"
						displayName="CloseSQLdm"
						moduleid="0fe8941e-6526-477a-bc6f-cb90c434e430"
						moduletype="UserCode"
						iteration="1"
						activity-exectype="runiteration"
						testentry-activity-type="testmodule">
						<errormessage>
							Exception has been thrown by the target of an invocation.
						</errormessage>
						<item
							timeRelativeToTestSuiteStartTime="00:00.526"
							timeRelativeToTestModuleStartTime="00:00.006"
							timeWallClock="06:22:32"
							time="00:00.526"
							level="Error"
							category="Module">
							<message>
								Exception has been thrown by the target of an invocation.<br/>The type initializer for 'AutomationSQLdm.Configuration.Config' threw an exception.<br/>Object reference not set to an instance of an object.
							</message>
							<metainfo
								stacktrace="   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean&amp; canBeCached, RuntimeMethodHandleInternal&amp; ctor, Boolean&amp; bNeedSecurityCheck)&#13;&#10;   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark&amp; stackMark)&#13;&#10;   at System.Activator.CreateInstance(Type type, Boolean nonPublic)&#13;&#10;   at System.Activator.CreateInstance(Type type)&#13;&#10;   at Ranorex.Core.Testing.TestModuleActivator.DefaultFactoryMethod.CreateFactory()&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.InitializeTestModuleInstance(TestModuleLeaf runTargetLeaf)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.RunWithRepeats(DataContext parentDataContext, ErrorBehavior errorBehavior)&#13;&#10;   at Ranorex.Core.Testing.TestModuleLeaf.Run(DataContext parentDataContext, Boolean childSkip)"
								loglvl="Error">
							</metainfo>
						</item>
					</activity>
				</activity>
			</activity>
		</activity>
	</activity>
</report>
